Fix kexec issue for kernel with patchlevel greater than 255
xcp-ng-rpms/kexec-tools pull request #1
Opened 2024-09-13 10:39 UTC by tescande

This backports the patch that removes the error prone kernel_version() function. This patch fixes the issue causing kexec to fail with a kernel version that has a patchlevel greater than 255.

2024-09-13 13:19 UTC, stormi approved these changes

2024-09-16 08:16 UTC, ydirson requested changes
Cannot find bb6f6f107190f2e6e90a272ea26edb172c37c452 in `linux.git` or `linux-stable.git`, where is it from?

2024-09-16 08:32 UTC, Nambrok commented
It's a commit from kexec-tools, another tree: https://git.kernel.org/pub/scm/utils/kernel/kexec/kexec-tools.git/commit/?h=bb6f6f107190f2e6e90a272ea26edb172c37c452

2024-09-16 08:38 UTC, Nambrok approved these changes

2024-09-16 09:04 UTC, ydirson approved these changes

2024-09-16 12:07 UTC, merged

2024-09-16 12:31 UTC, tescande commented
Koji build [v8.3-incoming](https://koji.xcp-ng.org//buildinfo?buildID=3492)